In [1]:
import numpy as np
from Molecule import Molecule
np.set_printoptions(precision=7, linewidth=120, suppress=True)


In [2]:
mol = Molecule('input/h2o/STO-3G/geom.dat')
nuclear_replusion = 'input/h2o/STO-3G/enuc.dat'
one_electron = 'input/h2o/STO-3G/s.dat'
kinetic_energy =  'input/h2o/STO-3G/t.dat'
nuclear_attraction =  'input/h2o/STO-3G/v.dat'
two_electron = 'input/h2o/STO-3G/eri.dat'



 

# Nuclear Repulsion Energy

In [3]:
with open(nuclear_replusion, 'r') as fp:
    nr = float(fp.readline().strip())

print(f'Nuclear repulsion energy = {nr}')

Nuclear repulsion energy = 8.00236706181045


In [4]:
print('Overlap Integral = ')
overlap_int =  mol.read_intregals(one_electron)
print(overlap_int)

print('Kinetic Energy Integral = ')
kinetic_int =  mol.read_intregals(kinetic_energy)
print(kinetic_int)

print('Nuclear Attraction  Integral = ')
nuclear_int =  mol.read_intregals(nuclear_attraction)
print(nuclear_int)

print('Core Hamiltonian = ')
H_core = kinetic_int + nuclear_int
print(H_core)

Overlap Integral = 
[[ 1.         0.2367039 -0.        -0.        -0.         0.0384056  0.0384056]
 [ 0.2367039  1.         0.        -0.         0.         0.3861388  0.3861388]
 [-0.         0.         1.        -0.         0.         0.2684382 -0.2684382]
 [-0.        -0.        -0.         1.        -0.         0.2097269  0.2097269]
 [-0.         0.         0.        -0.         1.        -0.        -0.       ]
 [ 0.0384056  0.3861388  0.2684382  0.2097269 -0.         1.         0.1817599]
 [ 0.0384056  0.3861388 -0.2684382  0.2097269 -0.         0.1817599  1.       ]]
Kinetic Energy Integral = 
[[29.0031999 -0.1680109  0.         0.        -0.        -0.0084164 -0.0084164]
 [-0.1680109  0.808128   0.        -0.         0.         0.0705174  0.0705174]
 [ 0.         0.         2.5287312 -0.         0.         0.1470909 -0.1470909]
 [ 0.        -0.        -0.         2.5287312 -0.         0.11492    0.11492  ]
 [-0.         0.         0.        -0.         2.5287312 -0.        -0. 

# Build the Orthogonal Matrix

In [5]:
# Diagonalize the overlap matrix:
eigvalue, eigvector = np.linalg.eigh(overlap_int)

#Build the symmetric orthogonalization matrix using:

S_ortho = eigvector @ np.diag(eigvalue**(-1/2)) @ eigvector.T

print('The S^-1/2 matrix is = ')
print(S_ortho)



The S^-1/2 matrix is = 
[[ 1.0236346 -0.1368547  0.        -0.0074873  0.         0.0190279  0.0190279]
 [-0.1368547  1.1578632 -0.         0.0721601 -0.        -0.2223326 -0.2223326]
 [ 0.        -0.         1.0733148 -0.        -0.        -0.1757583  0.1757583]
 [-0.0074873  0.0721601 -0.         1.038305  -0.        -0.1184626 -0.1184626]
 [ 0.        -0.        -0.        -0.         1.        -0.         0.       ]
 [ 0.0190279 -0.2223326 -0.1757583 -0.1184626 -0.         1.1297234 -0.0625975]
 [ 0.0190279 -0.2223326  0.1757583 -0.1184626  0.        -0.0625975  1.1297234]]


# Build the Initial Guess Density 

In [23]:
Fock = (S_ortho.T)@ H_core @ S_ortho
print('Initial Fock Matrix = ')
print(Fock)
F_eig_value, F_eig_vector = np.linalg.eigh(Fock)


C_0 = S_ortho @ (F_eig_vector)

print('Initial C matrix: ')
print(C_0)

# Density Matrix

occ = mol.occ
C_occ = C_0[:, :5]
# D_int = C_0[:, :5] @ C_0[:, :5].T 
D_int = np.einsum('pi,qi->pq', C_occ, C_occ, optimize=True)

print('Initial Density Matrix : ')
print(D_int)






Initial Fock Matrix = 
[[-32.2545866  -2.7914909  -0.          0.008611    0.         -0.1812967  -0.1812967]
 [ -2.7914909  -8.2368891   0.         -0.2282926  -0.         -0.3857987  -0.3857987]
 [ -0.          0.         -7.542889    0.          0.         -0.1132121   0.1132121]
 [  0.008611   -0.2282926   0.         -7.4570295  -0.         -0.1102196  -0.1102196]
 [  0.         -0.          0.         -0.         -7.3471449   0.         -0.       ]
 [ -0.1812967  -0.3857987  -0.1132121  -0.1102196   0.         -4.0329547  -0.0446466]
 [ -0.1812967  -0.3857987   0.1132121  -0.1102196  -0.         -0.0446466  -4.0329547]]
Initial C matrix: 
[[-1.0015436 -0.2336245 -0.         0.0856842 -0.        -0.0482226  0.       ]
 [ 0.0071893  1.0579388  0.        -0.3601105  0.         0.4631213 -0.       ]
 [-0.        -0.         1.0610702  0.         0.        -0.        -0.2965071]
 [ 0.0002671  0.4272843 -0.         0.9399425 -0.         0.2129401 -0.       ]
 [ 0.         0.        -0. 

# Compute the Inital SCF Energy

In [30]:
E_0 = np.einsum('pq,pq->', (H_core + Fock), D_int, optimize=True) + nr

print(E_0)



-121.84303146809549
